var sqeVocab = [
  {term:"1L", definition:"法学院一年级学生"},
  {term:"2L", definition:"法学院二年级学生"},
  {term:"3L", definition:"法学院三年级学生"},
  {term:"401(k) plan 401(k)", definition:"退休计划"},
  {term:"scam 419", definition:"诈骗 预付费诈骗（Advance-fee fraud）"},
  {term:"ABA", definition:"美国律师协会 American Bar Association"},
  {term:"ABM", definition:"反弹道导弹"},
  {term:"abatable nuisance", definition:"可减轻的侵扰"},
  {term:"abate", definition:"降低；减少；排除；撤销；中止"},
  {term:"abatement", definition:"减少；撤销；中止"},
  {term:"abatement of a legacy", definition:"遗产扣减"},
  {term:"abatement of taxes", definition:"税收减免"},
  {term:"abdicate", definition:"放弃（权力/职位）"},
  {term:"abduct", definition:"拐骗；诱拐；绑架"},
  {term:"abduction", definition:"诱拐；绑架"},
  {term:"abet", definition:"教唆；协助犯罪"},
  {term:"abettor", definition:"教唆犯；共犯"},
  {term:"abeyance", definition:"中止；待定状态"},
  {term:"ab initio", definition:"自始；从一开始"},
  {term:"abortionist", definition:"堕胎医师"},
  {term:"abridge", definition:"删节；缩短"},
  {term:"abrogate", definition:"废除；撤销"},
  {term:"abrogation", definition:"废除；撤销"},
  {term:"abscond", definition:"潜逃；逃跑；躲债"},
  {term:"absolve", definition:"宣告无罪"},
  {term:"abstract of record", definition:"案卷摘要"},
  {term:"abstract of title", definition:"产权摘要"},
  {term:"abuse of discretion", definition:"滥用自由裁量权"},
  {term:"abuse of process", definition:"滥用诉讼程序"},
  {term:"abut", definition:"毗邻；接界"},
  {term:"acceleration clause", definition:"加速条款"},
  {term:"acceptance, conditional", definition:"附条件承诺"},
  {term:"acceptance, implied", definition:"默示承诺"},
  {term:"acceptance of bribes", definition:"受贿"},
  {term:"access to justice", definition:"诉诸司法的权利"},
  {term:"accession", definition:"添附；取得"},
  {term:"accessory", definition:"从犯；附件"},
  {term:"accessory after the fact", definition:"事后从犯"},
  {term:"accessory before the fact", definition:"事前从犯"},
  {term:"accommodation", definition:"通融；便利"},
  {term:"accommodation loan", definition:"通融贷款"},
  {term:"accommodation note", definition:"通融票据"},
  {term:"accommodation party", definition:"票据通融人"},
  {term:"accomplice liability", definition:"共犯责任"},
  {term:"accord", definition:"协议；和解"},
  {term:"accord and satisfaction", definition:"和解与清偿"},
  {term:"accountability", definition:"责任"},
  {term:"accountant, certified public", definition:"注册会计师（CPA）"},
  {term:"account for", definition:"解释；说明"},
  {term:"accounting period", definition:"会计期间"},
  {term:"account payable", definition:"应付账款"},
  {term:"account receivable", definition:"应收账款"},
  {term:"accredit", definition:"授权；认可"},
  {term:"accrete", definition:"增长；添附"},
  {term:"accretion", definition:"添附；自然增长"},
  {term:"accrual", definition:"应计；累积"},
  {term:"accrual method", definition:"权责发生制"},
  {term:"accrue", definition:"产生；累积"},
  {term:"accrued interest", definition:"应计利息"},
  {term:"accusatory", definition:"控告的"},
  {term:"accused person", definition:"被告人"},
  {term:"acquiesce", definition:"默许；默认"},
  {term:"acquiescence", definition:"默许"},
  {term:"acquisition", definition:"收购；取得"},
  {term:"acquit", definition:"宣判无罪"},
  {term:"acquittal", definition:"宣告无罪；无罪判决"},
  {term:"acre", definition:"英亩"},
  {term:"acting", definition:"代理的；临时的"},
  {term:"action", definition:"诉讼；行为"},
  {term:"actionable", definition:"可诉的"},
  {term:"actionable per se", definition:"本身可诉"},
  {term:"action at equity", definition:"衡平法诉讼"},
  {term:"action at law", definition:"普通法诉讼"},
  {term:"active concealment", definition:"故意隐瞒"},
  {term:"active duty", definition:"现役"},
  {term:"active negligence", definition:"故意过失"},
  {term:"actual authority", definition:"实际授权"},
  {term:"actual residence", definition:"实际居住地"},
  {term:"act of God", definition:"不可抗力；天灾"},
  {term:"actuarial tables", definition:"精算表"},
  {term:"actuary", definition:"精算师"},
  {term:"actus reus", definition:"犯罪行为（客观要件）"},
  {term:"ADA", definition:"美国残疾人法案"},
  {term:"ad damnum", definition:"请求赔偿金额"},
  {term:"ADEA", definition:"就业年龄歧视法"},
  {term:"adeem", definition:"撤销遗赠"},
  {term:"ademption", definition:"遗赠失效"},
  {term:"adequate care", definition:"适当注意义务"},
  {term:"adequate compensation", definition:"适当赔偿"},
  {term:"adequate remedy at law", definition:"法律上的充分救济"},
  {term:"adhesion", definition:"附合；依附"},
  {term:"adhesion contract", definition:"附合合同；格式合同"},
  {term:"ad hoc", definition:"特别的；专门的"},
  {term:"ad hominem", definition:"人身攻击的"},
  {term:"ad infinitum", definition:"无限地"},
  {term:"adjacent", definition:"相邻的"},
  {term:"adjective law", definition:"程序法"},
  {term:"adjoining", definition:"毗邻的；接壤的"},
  {term:"adjourn", definition:"休庭；延期"},
  {term:"adjudicate", definition:"裁决；判决"},
  {term:"adjudication", definition:"判决；裁定；判定"},
  {term:"adjusted basis", definition:"调整后基数"},
  {term:"adjusted gross income", definition:"调整后总收入"},
  {term:"adjuster", definition:"理赔员"},
  {term:"ad litem", definition:"诉讼代理人；专为诉讼指定的"},
  {term:"ad litem, guardian", definition:"诉讼监护人"},
  {term:"administer", definition:"管理；执行"},
  {term:"administrative", definition:"行政的"},
  {term:"administrative agency", definition:"行政机关"},
  {term:"administrative hearing", definition:"行政听证"},
  {term:"administrative law", definition:"行政法"},
  {term:"administrative law judge", definition:"行政法官"},
  {term:"Administrative Procedure Act", definition:"行政程序法"},
  {term:"administrator", definition:"遗产管理人；行政官"},
  {term:"admiralty and maritime jurisdiction", definition:"海事管辖权"},
  {term:"admiralty court", definition:"海事法院"},
  {term:"admissible evidence", definition:"可接纳的证据；可采纳证据"},
  {term:"admitted into evidence", definition:"接收为证据"},
  {term:"admission of evidence", definition:"证据采纳"},
  {term:"adulterate", definition:"掺假；掺杂"},
  {term:"adultery", definition:"通奸"},
  {term:"ad valorem tax", definition:"从价税"},
  {term:"advance", definition:"预付款；提前支付"},
  {term:"advance directive", definition:"预先医疗指示"},
  {term:"advancement", definition:"预付遗产"},
  {term:"advance sheets", definition:"判例活页汇编"},
  {term:"adversarial", definition:"对抗制的"},
  {term:"adversary", definition:"对方；对手"},
  {term:"adversary proceeding", definition:"对抗式程序"},
  {term:"adverse", definition:"不利的；相反的"},
  {term:"adverse claim", definition:"反向主张"},
  {term:"adverse possession", definition:"逆权占有；时效占有"},
  {term:"advisory opinion", definition:"咨询意见"},
  {term:"advocacy", definition:"辩护；代理"},
  {term:"advocacy, trial", definition:"庭审辩护"},
  {term:"advocate", definition:"辩护人；律师；倡导"},
  {term:"adware", definition:"广告软件"},
  {term:"aesthetic value", definition:"审美价值"},
  {term:"affiant", definition:"宣誓人；立誓人"},
  {term:"affidavit", definition:"宣誓书；经宣誓的书面陈述"},
  {term:"affidavit evidence", definition:"宣誓书证据"},
  {term:"affiliate", definition:"关联机构；附属"},
  {term:"affiliation", definition:"附属关系"},
  {term:"affinity", definition:"姻亲关系"},
  {term:"affirmation", definition:"郑重声明；确认"},
  {term:"affirmative action", definition:"平权行动；积极行动"},
  {term:"affirmative defense", definition:"积极抗辩"},
  {term:"affirmative misconduct", definition:"故意不当行为"},
  {term:"affirmative relief", definition:"积极救济"},
  {term:"affix", definition:"粘贴；附加"},
  {term:"AFL-CIO", definition:"美国劳工联合会"},
  {term:"aforesaid", definition:"前述的"},
  {term:"aforethought", definition:"预谋的"},
  {term:"a fortiori", definition:"更有理由"},
  {term:"after-acquired property", definition:"后取得财产"},
  {term:"after-acquired title", definition:"后取得产权"},
  {term:"after the fact", definition:"事后的"},
  {term:"against interest", definition:"对己不利"},
  {term:"against the law", definition:"违法"},
  {term:"against the weight of evidence", definition:"违背证据优势"},
  {term:"against the will", definition:"违背意愿"},
  {term:"age discrimination", definition:"年龄歧视"},
  {term:"Age Discrimination in Employment Act", definition:"就业年龄歧视法"},
  {term:"agency agreement", definition:"代理协议"},
  {term:"age of consent", definition:"同意年龄"},
  {term:"age of majority", definition:"成年年龄"},
  {term:"age of reason", definition:"理性年龄（通常7岁"},
  {term:"aggravated", definition:"加重的"},
  {term:"aggravated assault", definition:"严重袭击"},
  {term:"aggravated circumstances", definition:"增加严重性的情节；加重情节"},
  {term:"aggrieved", definition:"受害的"},
  {term:"aggrieved party", definition:"受害方"},
  {term:"aging of accounts", definition:"账龄分析"},
  {term:"agrarian", definition:"土地的；农业的"},
  {term:"aid and abet", definition:"协助与教唆；协谋；帮凶"},
  {term:"aiding escape", definition:"协助逃跑"},
  {term:"aiding prostitution", definition:"协助卖淫"},
  {term:"air rights", definition:"空间权"},
  {term:"aka", definition:"又名"},
  {term:"alderman", definition:"市议员"},
  {term:"aleatory", definition:"偶然的；射幸的"},
  {term:"aleatory contract", definition:"射幸合同"},
  {term:"alias", definition:"别名；化名；假名"},
  {term:"alibi", definition:"不在场证明；不在现场的证据"},
  {term:"alien", definition:"外国人；外侨；侨民"},
  {term:"alienable", definition:"可转让的"},
  {term:"alienate", definition:"转让；让与"},
  {term:"alienation", definition:"转让；让与"},
  {term:"alienation of affections", definition:"感情移情侵权；感情转移侵权"},
  {term:"alimony", definition:"赡养费；扶养费"},
  {term:"allege", definition:"声称；指称；指控"},
  {term:"alleged thief", definition:"被指称为窃贼的人"},
  {term:"allocation", definition:"分配"},
  {term:"allocution", definition:"认罪供词；自白供词"},
  {term:"amnesty", definition:"大赦"},
  {term:"amicable", definition:"友好的；和解的"},
  {term:"ancillary relief", definition:"附属救济"},
  {term:"animal control officer", definition:"动物检疫人员"},
  {term:"animal cruelty", definition:"虐畜罪"},
  {term:"antenuptial agreement", definition:"婚前协议"},
  {term:"anticompetitive practices", definition:"防止竞争措施"},
  {term:"anticipatory breach", definition:"预期违约"},
  {term:"antitrust act", definition:"反托拉斯法案；反垄断法案"},
  {term:"appeal", definition:"上诉"},
  {term:"appearance", definition:"出庭"},
  {term:"appellant", definition:"上诉人"},
  {term:"appellate court", definition:"上诉法庭"},
  {term:"appellate jurisdiction", definition:"上诉管辖权"},
  {term:"applicability", definition:"可适应性"},
  {term:"appurtenant", definition:"附属的；从属的"},
  {term:"arm of the law", definition:"法律的权利"},
  {term:"arraignment", definition:"传讯；提审"},
  {term:"arson", definition:"纵火罪"},
  {term:"articles of association", definition:"公司章程"},
  {term:"asylum", definition:"庇护"},
  {term:"assailant", definition:"攻击者"},
  {term:"assault and battery", definition:"殴打罪；伤害人身罪"},
  {term:"assassin", definition:"刺客；暗杀凶手"},
  {term:"assignment", definition:"转让；让与"},
  {term:"assurance", definition:"保险；保证"},
  {term:"attachment", definition:"扣押；附加"},
  {term:"aspersion", definition:"中伤；诽谤"},
  {term:"attempted crime", definition:"犯罪未遂"},
  {term:"attempted murder", definition:"谋杀未遂"},
  {term:"attorney-client privilege", definition:"律师---客户特权"},
  {term:"authentication", definition:"认证；证实"},
  {term:"authenticate", definition:"鉴定；认证"},
  {term:"auto burglary", definition:"偷汽车里的东西"},
  {term:"auto theft", definition:"偷汽车"},
  {term:"autopsy", definition:"验尸；尸体剖检"},
  {term:"award", definition:"裁定额；判给B"},
  {term:"back pay", definition:"拖欠工资"},
  {term:"back wages", definition:"拖欠工资"},
  {term:"badge (of a police officer)", definition:"徽章"},
  {term:"bad check", definition:"空头支票"},
  {term:"bad debt", definition:"坏账"},
  {term:"bad faith", definition:"恶意；不诚信"},
  {term:"bait and switch", definition:"诱饵调包欺诈"},
  {term:"bail", definition:"保释；保释金"},
  {term:"bail bond", definition:"保释保证书；保释保证金"},
  {term:"bail bondsman", definition:"保释代理人"},
  {term:"bail forfeiture", definition:"保释金没收"},
  {term:"bail jumping", definition:"弃保潜逃；逃保"},
  {term:"Bail Reform Act", definition:"保释修正案"},
  {term:"bailee", definition:"受托人"},
  {term:"bailey", definition:"法庭"},
  {term:"bailiff", definition:"法警；法庭执行官；执达员"},
  {term:"bailment", definition:"寄托；保管"},
  {term:"bailor", definition:"寄托人"},
  {term:"balance sheet", definition:"资产负债表"},
  {term:"balance of probabilities", definition:"盖然性权衡"},
  {term:"balloon mortgage", definition:"气球式抵押贷款"},
  {term:"bankruptcy, Chapter 7", definition:"第七章破产（清算）"},
  {term:"bankruptcy, Chapter 11", definition:"第十一章破产（重整）"},
  {term:"bankruptcy, Chapter 12", definition:"第十二章破产（农户）"},
  {term:"bankruptcy, Chapter 13", definition:"第十三章破产（个人重整）"},
  {term:"bankruptcy order", definition:"破产令"},
  {term:"bandit", definition:"盗贼；土匪"},
  {term:"banish", definition:"流放；驱逐"},
  {term:"bar association", definition:"律师协会"},
  {term:"barratry", definition:"挑讼；非法挑诉"},
  {term:"barricade", definition:"临时防御；障碍物"},
  {term:"beforehand", definition:"事先；预先"},
  {term:"befouling water", definition:"污染水源"},
  {term:"bench", definition:"法官席；法庭；法官"},
  {term:"bench trial", definition:"法官审理（无陪审团）审讯"},
  {term:"bench warrant", definition:"法庭传票"},
  {term:"beyond reasonable doubt", definition:"无合理怀疑；理无可置疑"},
  {term:"bias", definition:"偏见；偏袒"},
  {term:"bicameral", definition:"两院制的"},
  {term:"bigamy", definition:"重婚罪；一夫多妻制"},
  {term:"bill (in a legislature)", definition:"议案"},
  {term:"bill of lading", definition:"提货单；提单"},
  {term:"bill of particular", definition:"诉讼明细书；索赔清单"},
  {term:"Bill of Rights", definition:"人权法案；基本权利法案"},
  {term:"bind over", definition:"责令待审"},
  {term:"binding", definition:"有约束力的；附有义务的"},
  {term:"binding agreement", definition:"有约束力的协议"},
  {term:"birthright", definition:"与生俱来的权利"},
  {term:"blood alcohol", definition:"血液内的酒精含量"},
  {term:"bludgeon", definition:"杖刑"},
  {term:"board certified (medical)", definition:"拥有医学公会认可的资格执照"},
  {term:"board examiner (medical)", definition:"医学公会监考员"},
  {term:"boating infractions", definition:"划船游乐方面的违规"},
  {term:"book (v)", definition:"入案；落案"},
  {term:"bookie /bookmaker", definition:"赌博经纪人"},
  {term:"bookmaking", definition:"外围下注"},
  {term:"bond", definition:"保证；债券"},
  {term:"bastard", definition:"非婚生子女"},
  {term:"battery", definition:"殴打；非法接触；人身侵犯"},
  {term:"bearer", definition:"持票人"},
  {term:"bearer paper", definition:"不记名票据"},
  {term:"beneficial interest", definition:"受益权"},
  {term:"beneficial owner", definition:"受益所有人"},
  {term:"beneficiary", definition:"受益人"},
  {term:"bequeath", definition:"遗赠（动产）"},
  {term:"bequest", definition:"遗赠"},
  {term:"best evidence rule", definition:"最佳证据规则"},
  {term:"bidder", definition:"投标人"},
  {term:"bona fide", definition:"善意；真诚"},
  {term:"bribery", definition:"贿赂"},
  {term:"burden of proof", definition:"举证责任"},
  {term:"burglary", definition:"盗窃；盗窃罪；入室盗窃罪"},
  {term:"business license", definition:"营业执照"},
  {term:"bylaws", definition:"规章；规程"},
  {term:"campaign contribution", definition:"竞选捐献；竞选献金"},
  {term:"cannabis", definition:"大麻；大麻类毒品"},
  {term:"capital gain", definition:"资本利得"},
  {term:"capital loss", definition:"资本损失"},
  {term:"capital punishment", definition:"死刑"},
  {term:"carcass", definition:"动物尸体"},
  {term:"carjacking", definition:"劫车"},
  {term:"carpool lane", definition:"合用车专用道"},
  {term:"carrying a concealed weapon", definition:"身携暗器；携带暗器"},
  {term:"case in chief", definition:"主案；控方的证据"},
  {term:"case law", definition:"判例法；案例"},
  {term:"cash method", definition:"现金制"},
  {term:"causation", definition:"因果关系；造事原因"},
  {term:"cause of action", definition:"诉因"},
  {term:"causing catastrophe", definition:"造成大灾难"},
  {term:"caveat", definition:"警告；中止诉讼的通知"},
  {term:"caveat emptor", definition:"买者自负"},
  {term:"cease and desist", definition:"停止；制止"},
  {term:"census", definition:"人口普查；人口调查"},
  {term:"certificate of title", definition:"产权证书"},
  {term:"certified", definition:"被证明的；有保证的"},
  {term:"certified copy", definition:"认证副本"},
  {term:"certiorari", definition:"调卷令"},
  {term:"challenge for cause", definition:"有原因要求陪审员退席"},
  {term:"champerty", definition:"帮讼牟利"},
  {term:"chancellor", definition:"大法官"},
  {term:"chancery", definition:"衡平法院"},
  {term:"charge", definition:"指控；抵押"},
  {term:"charge to the jury （", definition:"法官）对陪审团的指导"},
  {term:"charging order", definition:"扣押令"},
  {term:"charges", definition:"指控；罪名"},
  {term:"charitable organization", definition:"慈善机构；慈善组织"},
  {term:"charity drive", definition:"慈善活动"},
  {term:"chattel", definition:"动产；有形财产"},
  {term:"chattel personal", definition:"私人动产"},
  {term:"chattel real", definition:"准不动产（租赁）"},
  {term:"check", definition:"支票"},
  {term:"chief justice", definition:"首席法官"},
  {term:"child endangerment", definition:"危害儿童"},
  {term:"child labor law", definition:"童工法"},
  {term:"child molestation", definition:"猥亵儿童"},
  {term:"child support", definition:"子女抚养费"},
  {term:"child welfare service", definition:"儿童福利服务"},
  {term:"choking", definition:"窒息"},
  {term:"circuit court", definition:"巡回法庭"},
  {term:"circumstantial evidence", definition:"间接证据；情况证据；旁证"},
  {term:"citation", definition:"罚单；传票；传唤；引用"},
  {term:"civil case", definition:"民事案件"},
  {term:"civil code", definition:"民事法典"},
  {term:"civil enforcement", definition:"执行民事法典"},
  {term:"civil law", definition:"民法；大陆法系"},
  {term:"civil liability", definition:"民事责任"},
  {term:"civil liberty", definition:"公民自由"},
  {term:"civil right", definition:"公民权利"},
  {term:"claimant", definition:"债权人；原告；索赔人"},
  {term:"clandestine", definition:"暗中的；秘密的"},
  {term:"class action lawsuit", definition:"集体诉讼"},
  {term:"clean hands", definition:"干净之手原则"},
  {term:"clear and convincing", definition:"清晰且有说服力的"},
  {term:"clerk", definition:"书记员；职员；法庭书记"},
  {term:"closing argument", definition:"终结陈述；终结辩论"},
  {term:"cocaine", definition:"古柯碱；可卡因；白粉"},
  {term:"code of conduct", definition:"行为准则"},
  {term:"co-defendant", definition:"共同被告"},
  {term:"cognizant", definition:"知晓的"},
  {term:"co-ownership", definition:"共同所有"},
  {term:"co-conspirator", definition:"共谋人；篡谋人"},
  {term:"coercion", definition:"强迫；威胁；压制"},
  {term:"cohabitation", definition:"同居"},
  {term:"collateral", definition:"担保物；附属的"},
  {term:"collateral estoppel", definition:"间接禁反言"},
  {term:"collective bargaining", definition:"集体谈判"},
  {term:"collusion", definition:"串通；共谋"},
  {term:"color of law", definition:"表面合法"},
  {term:"comity", definition:"礼让；司法尊重"},
  {term:"commercial drivers license", definition:"商业性驾驶执照"},
  {term:"commitment", definition:"承诺；关押"},
  {term:"commitment hearing", definition:"拘禁听证"},
  {term:"common carrier", definition:"公共承运人"},
  {term:"common law marriage", definition:"普通法婚姻；习惯法婚姻"},
  {term:"community property", definition:"夫妻共同财产"},
  {term:"community service", definition:"社区服务"},
  {term:"community standards", definition:"共同道德标准"},
  {term:"commutation", definition:"减刑"},
  {term:"compelling argument", definition:"有说服力的争辩"},
  {term:"compensatory damages", definition:"补偿性赔偿"},
  {term:"competent council", definition:"称职的律师"},
  {term:"competent court", definition:"管辖法院；主管法院"},
  {term:"complaint", definition:"控诉；民事起诉；起诉状；控告"},
  {term:"compulsory education", definition:"义务教育"},
  {term:"concealed firearm", definition:"夹藏的枪械"},
  {term:"concealed weapon", definition:"夹藏武器；暗器"},
  {term:"concurrent sentences", definition:"合并刑期；同时执行"},
  {term:"confession", definition:"认罪；供认；招认；供述"},
  {term:"confinement", definition:"监禁；拘留"},
  {term:"confiscate", definition:"没收；充公"},
  {term:"confrontation of witness", definition:"证人对质"},
  {term:"consecutive sentences", definition:"连续刑期"},
  {term:"conspiracy to commit a crime", definition:"篡谋犯罪"},
  {term:"constable", definition:"警察"},
  {term:"constitutional right", definition:"宪法权利"},
  {term:"contempt of court", definition:"蔑视法庭"},
  {term:"continuance/continuation", definition:"诉讼延期；展延"},
  {term:"contradict", definition:"反驳"},
  {term:"contradict oneself", definition:"自相矛盾"},
  {term:"contradiction", definition:"矛盾"},
  {term:"convict", definition:"罪犯；定罪"},
  {term:"conviction", definition:"定罪；判罪"},
  {term:"coroner", definition:"验尸官"},
  {term:"correctional officer", definition:"狱警；监管警员"},
  {term:"corroborate", definition:"证实"},
  {term:"corpus delicti", definition:"犯罪事实"},
  {term:"counseling", definition:"心理辅导"},
  {term:"count", definition:"罪项"},
  {term:"court appointed attorney", definition:"法庭任命的律师；法庭指派律师"},
  {term:"court interpreter", definition:"法庭翻译；法庭传译"},
  {term:"court of appeals", definition:"上诉法院"},
  {term:"court of last resort", definition:"终审法院"},
  {term:"court of record", definition:"案件记录所在的法院"},
  {term:"court order", definition:"法院命令"},
  {term:"credibility", definition:"可信度；可信性"},
  {term:"crime lab", definition:"罪证化验室"},
  {term:"criminal background information", definition:"前科资料"},
  {term:"criminal code", definition:"刑事法典"},
  {term:"criminal information", definition:"刑事检举书"},
  {term:"criminal intent", definition:"犯罪意图"},
  {term:"criminal justice", definition:"刑事司法"},
  {term:"criminal mischief", definition:"刑事恶作剧"},
  {term:"criminal offense", definition:"刑事犯罪"},
  {term:"criminal proceedings", definition:"刑事诉讼程序"},
  {term:"criminal trespass", definition:"非法侵入他人土地或房屋"},
  {term:"cross‑examination", definition:"盘问；交叉询问"},
  {term:"crosswalk", definition:"行人穿越道；斑马线；人行横道"},
  {term:"cruelty", definition:"虐待"},
  {term:"curfew", definition:"宵禁；戒严"},
  {term:"custodial interference", definition:"妨碍监护权"},
  {term:"custody", definition:"监护权；羁押；保管；拘留"},
  {term:"consequential damages", definition:"间接损失"},
  {term:"conservator", definition:"监护人；监管人"},
  {term:"consideration", definition:"对价"},
  {term:"consign", definition:"交付；托付"},
  {term:"consortium", definition:"配偶权利"},
  {term:"constructive", definition:"推定的；拟制的"},
  {term:"constructive trust", definition:"推定信托"},
  {term:"contentious", definition:"有争议的"},
  {term:"contingency", definition:"偶然性；或有事项"},
  {term:"contingent beneficiary", definition:"或有受益人"},
  {term:"contributory negligence", definition:"共同过失"},
  {term:"conversion", definition:"侵占动产"},
  {term:"counterclaim", definition:"反诉"},
  {term:"covenant", definition:"契约；约定"},
  {term:"cruelty", definition:"虐待"},
  {term:"DA (District Attorney)", definition:"检察官；检控官"},
  {term:"days of grace", definition:"宽限期"},
  {term:"de facto", definition:"事实上；实际上"},
  {term:"de jure", definition:"法理上"},
  {term:"deadly weapon", definition:"致命武器"},
  {term:"death sentence", definition:"死刑"},
  {term:"debrief (a witness)", definition:"询问证人"},
  {term:"deceit", definition:"欺骗；欺诈"},
  {term:"deception", definition:"欺瞒；蒙骗"},
  {term:"decree", definition:"判决；法令；颁布法令"},
  {term:"deface", definition:"污损；毁伤外貌"},
  {term:"defamation", definition:"诽谤"},
  {term:"default", definition:"缺席；逾期未..."},
  {term:"default judgment", definition:"缺席判决"},
  {term:"defendant", definition:"被告"},
  {term:"defense attorney", definition:"辩护律师"},
  {term:"defense exhibit A", definition:"辩方证物甲"},
  {term:"deferred prosecution", definition:"缓期起诉"},
  {term:"defraud", definition:"诈骗；欺诈"},
  {term:"defunct", definition:"已倒闭；已失效；已死的；已故的"},
  {term:"delinquency", definition:"逾期；少年犯罪"},
  {term:"demolish", definition:"拆毁；拆除"},
  {term:"demurrer", definition:"异议；驳回申请"},
  {term:"denounce", definition:"谴责；斥责；驳斥"},
  {term:"department of corrections", definition:"监狱局；惩治局；狱政局"},
  {term:"department of motor vehicles", definition:"机动车辆管理局；车管局"},
  {term:"department of public safety", definition:"公安局；公安机关"},
  {term:"de novo", definition:"重新审理"},
  {term:"dependency", definition:"抚养"},
  {term:"deportation", definition:"递解出境；驱逐出境"},
  {term:"deposition", definition:"宣誓证言；宣誓证词；庭外取证；证词"},
  {term:"deprave", definition:"腐化；腐败"},
  {term:"deputy D.A.", definition:"地区副检控官"},
  {term:"deputy sheriff", definition:"警员"},
  {term:"desecration", definition:"亵渎；污辱"},
  {term:"destruction of property", definition:"破坏财物"},
  {term:"detain", definition:"扣留；拘留"},
  {term:"detainer", definition:"拘留；扣押；扣押令"},
  {term:"detention", definition:"拘留"},
  {term:"dictum", definition:"附带意见；判例附带意见"},
  {term:"diminished capacity", definition:"责任能力减弱"},
  {term:"diminution", definition:"减少；缩减"},
  {term:"direct examination", definition:"直接询问"},
  {term:"directive", definition:"指令"},
  {term:"disaffirm", definition:"撤销；否认"},
  {term:"disbar", definition:"取消律师资格"},
  {term:"discharge", definition:"解除；清偿；释放；撤销命令"},
  {term:"discontinuance", definition:"中止诉讼"},
  {term:"discovery", definition:"证据开示；透露证据；告知准备使用的证据"},
  {term:"discretion", definition:"自由裁量权"},
  {term:"discrimination", definition:"歧视"},
  {term:"disloyalty", definition:"不忠诚"},
  {term:"dismissal", definition:"驳回；解雇"},
  {term:"dismiss with prejudice", definition:"有偏见驳回（不得再诉）"},
  {term:"dismiss without prejudice", definition:"无偏见驳回（可再诉）"},
  {term:"disorderly conduct", definition:"扰乱治安行为；行为不轨"},
  {term:"disposition", definition:"处置；分配；（未成年人）判决、处理"},
  {term:"dissident", definition:"异议人士；持不同政见者"},
  {term:"dissolution", definition:"解散；解除"},
  {term:"distraint", definition:"扣押财物"},
  {term:"distress", definition:"扣押财物；痛苦"},
  {term:"disturbing public meeting", definition:"扰乱公众会议"},
  {term:"disturbing the peace", definition:"扰乱治安"},
  {term:"diversion", definition:"转移法律程序；替换"},
  {term:"divest", definition:"剥夺"},
  {term:"docket", definition:"案件目录；法院日程表"},
  {term:"docket sheet", definition:"法院日程表"},
  {term:"domain", definition:"领域；所有权"},
  {term:"domestic violence", definition:"家庭暴力"},
  {term:"domicile", definition:"住所地；户籍"},
  {term:"dominant estate", definition:"需役地"},
  {term:"donee", definition:"受赠人"},
  {term:"donor", definition:"捐赠人"},
  {term:"double jeopardy", definition:"一罪不二审；双重审判"},
  {term:"dowry", definition:"嫁妆"},
  {term:"draft", definition:"汇票；草案"},
  {term:"duress", definition:"胁迫"},
  {term:"diversity jurisdiction", definition:"异籍管辖权"},
  {term:"eavesdropping", definition:"窃听；偷听"},
  {term:"easement appurtenant", definition:"从属地役权"},
  {term:"easement in gross", definition:"独立地役权"},
  {term:"ejectment", definition:"收回不动产之诉"},
  {term:"electric chair", definition:"电椅；电刑"},
  {term:"electronic monitoring", definition:"电子监视"},
  {term:"embezzlement", definition:"侵占；挪用；盗用；监守自盗"},
  {term:"emergency medical service", definition:"急救服务"},
  {term:"eminent domain", definition:"国家征用权；征用权"},
  {term:"en banc", definition:"全体法官出庭"},
  {term:"endorsement", definition:"背书；批注"},
  {term:"enjoin", definition:"禁止；强制"},
  {term:"entitlement", definition:"权利；资格"},
  {term:"equitable", definition:"衡平法的"},
  {term:"escape clause", definition:"免责条款"},
  {term:"examination", definition:"审查；发问；盘问；询问"},
  {term:"exception", definition:"异议"},
  {term:"excess", definition:"超额"},
  {term:"executor", definition:"遗嘱执行人"},
  {term:"exemplary damages", definition:"惩罚性赔偿"},
  {term:"exemption", definition:"豁免；免税"},
  {term:"exhibit", definition:"证据；展示；证物；呈物"},
  {term:"exigent circumstances", definition:"紧急情况"},
  {term:"ex officio", definition:"依职权"},
  {term:"ex parte", definition:"单方面的"},
  {term:"express warranty", definition:"明示担保"},
  {term:"expropriation", definition:"征收"},
  {term:"excusable homicide", definition:"可原谅的杀人"},
  {term:"exculpatory", definition:"申明无罪的"},
  {term:"exoneration", definition:"证明无罪；免除责任"},
  {term:"exoneration of bail", definition:"免除保释金"},
  {term:"exploitation", definition:"利用；剥削"},
  {term:"expose (a crime)", definition:"揭露；揭发"},
  {term:"expunge", definition:"删除；剔除；消除记录"},
  {term:"extortion", definition:"勒索；敲诈勒索"},
  {term:"extradition", definition:"引渡"},
  {term:"fabrication", definition:"捏造；伪造"},
  {term:"failure to appear", definition:"不出庭罪"},
  {term:"fair use", definition:"公平使用"},
  {term:"fallacy", definition:"谬论"},
  {term:"false accusation", definition:"诬告罪"},
  {term:"false alarm", definition:"虚惊"},
  {term:"false arrest", definition:"非法逮捕"},
  {term:"false imprisonment", definition:"非法拘禁"},
  {term:"false pretenses", definition:"欺诈手段"},
  {term:"falsification of documents", definition:"伪造文件"},
  {term:"falsification of evidence", definition:"伪造证据"},
  {term:"felony", definition:"重罪"},
  {term:"fencing", definition:"买卖赃物"},
  {term:"field sobriety test", definition:"现场清醒测试"},
  {term:"final judgment", definition:"终局判决"},
  {term:"fixture", definition:"固定附着物"},
  {term:"firearms", definition:"枪械"},
  {term:"fire code", definition:"防火规章"},
  {term:"fire marshal", definition:"消防局长"},
  {term:"fire prevention", definition:"防火措施"},
  {term:"for the record", definition:"记录在案"},
  {term:"foreclosure", definition:"止赎；取消赎回权；赎回权取消"},
  {term:"forensic", definition:"法庭的；法医的"},
  {term:"forensic expert", definition:"法医；科学鉴定专家"},
  {term:"forensic psychiatry", definition:"司法精神病学"},
  {term:"forensic science", definition:"司法科学；科学鉴定学"},
  {term:"forensics", definition:"法医学"},
  {term:"forfeit", definition:"放弃；失去"},
  {term:"forgery", definition:"伪造"},
  {term:"fornication", definition:"私通"},
  {term:"foster home", definition:"寄养家庭；收养所"},
  {term:"foul language", definition:"粗话"},
  {term:"fraudulent", definition:"欺诈的"},
  {term:"freehold", definition:"永久产权"},
  {term:"frisk", definition:"搜身"},
  {term:"fugitive", definition:"逃犯"},
  {term:"found liable", definition:"判定有责任"},
  {term:"frame up", definition:"造假陷害"},
  {term:"gag order", definition:"禁止谈论令"},
  {term:"gallows", definition:"绞刑台"},
  {term:"gaming", definition:"赌博；赌赛"},
  {term:"gang", definition:"帮派；团伙"},
  {term:"garnishee", definition:"第三债务人"},
  {term:"garnishment", definition:"扣押债权；扣押钱财"},
  {term:"gas chamber", definition:"毒气室"},
  {term:"genocide", definition:"种族灭绝"},
  {term:"gimmick", definition:"手法；手段"},
  {term:"gist", definition:"主旨；要点；大意"},
  {term:"good cause", definition:"正当理由"},
  {term:"good faith effort", definition:"真诚努力"},
  {term:"graffiti", definition:"乱涂乱写"},
  {term:"graft", definition:"受贿；渎职"},
  {term:"grand jury", definition:"大陪审团"},
  {term:"grand theft", definition:"重大盗窃罪"},
  {term:"grievously sinful", definition:"罪孽深重"},
  {term:"grievance", definition:"不满；冤情"},
  {term:"gross negligence", definition:"严重过失；重大疏忽"},
  {term:"ground", definition:"理由"},
  {term:"groundless", definition:"无根据；没道理"},
  {term:"guardian", definition:"监护人"},
  {term:"guardian ad litem", definition:"诉讼监护人"},
  {term:"gun runner", definition:"军火走私贩"},
  {term:"gunshot wound", definition:"枪伤"},
  {term:"grant", definition:"授予；转让"},
  {term:"habeas corpus", definition:"人身保护令"},
  {term:"habitual sex offender", definition:"性惯犯"},
  {term:"habitual violent offender", definition:"暴力惯犯"},
  {term:"hallucinogen", definition:"幻觉剂；致幻剂"},
  {term:"handcuff", definition:"手铐"},
  {term:"handgun", definition:"手枪"},
  {term:"harassment", definition:"骚扰"},
  {term:"harbor a criminal", definition:"窝藏罪犯"},
  {term:"hate crime", definition:"仇恨犯罪"},
  {term:"hazardous material", definition:"危险物品；有害材料"},
  {term:"hazing", definition:"戏弄；恶作剧"},
  {term:"hearsay", definition:"传闻证据"},
  {term:"heir", definition:"继承人"},
  {term:"hereditament", definition:"不动产"},
  {term:"highway patrol", definition:"高速公路巡警"},
  {term:"hijacking", definition:"劫持"},
  {term:"hit and run", definition:"肇事逃逸"},
  {term:"hoarding", definition:"囤积"},
  {term:"hoax", definition:"骗局；恶作剧"},
  {term:"home detention", definition:"软禁；居家监禁"},
  {term:"homicide", definition:"杀人；他杀"},
  {term:"hostage", definition:"人质"},
  {term:"hostile possession", definition:"恶意占有"},
  {term:"hostile witness", definition:"敌对证人"},
  {term:"hot pursuit", definition:"紧急追捕；紧追"},
  {term:"hung jury", definition:"悬而未决陪审团；悬置陪审团"},
  {term:"hunting tag", definition:"狩猎标牌"},
  {term:"illegal alien", definition:"非法居留者；非法外国人"},
  {term:"illegal immigration", definition:"非法移民"},
  {term:"illegal immigration broker", definition:"蛇头"},
  {term:"illegitimate child", definition:"私生子；非婚生子女"},
  {term:"illicit", definition:"非法的；不正当的"},
  {term:"immovable", definition:"不可移动的；不动产"},
  {term:"immunity from liability", definition:"责任豁免权"},
  {term:"immunity from prosecution", definition:"检控豁免权"},
  {term:"impeachment of witness", definition:"质疑证人；弹劾证人"},
  {term:"impersonation of judge", definition:"假扮法官"},
  {term:"impersonation of police officer", definition:"假扮警察"},
  {term:"implicate", definition:"牵连；牵涉"},
  {term:"implied consent", definition:"默示同意；默认"},
  {term:"implied warranty", definition:"默示担保"},
  {term:"impound", definition:"没收；扣押；充公"},
  {term:"imprisonment", definition:"监禁；徒刑"},
  {term:"in camera", definition:"不公开审理；秘密审议"},
  {term:"in session", definition:"开庭"},
  {term:"inadmissible", definition:"不可采纳的"},
  {term:"incarceration", definition:"监禁；关押；监禁"},
  {term:"incest", definition:"乱伦"},
  {term:"inchoate offenses", definition:"未完成罪；犯罪未遂"},
  {term:"incite", definition:"煽动；鼓动"},
  {term:"inconsistent (statements)", definition:"矛盾（供词）"},
  {term:"incriminate", definition:"归罪；使负罪"},
  {term:"indictment", definition:"大陪审团起诉书；公诉书"},
  {term:"indigent", definition:"贫穷的；贫困的"},
  {term:"inducement", definition:"诱惑；引诱"},
  {term:"infiltration", definition:"渗透"},
  {term:"influence peddling", definition:"权钱交易；招权纳贿"},
  {term:"informant", definition:"告密者；线人"},
  {term:"information", definition:"正式起诉书；刑事告发状"},
  {term:"informed consent", definition:"知情同意"},
  {term:"infraction", definition:"违规；违例；轻微违法；轻微违法"},
  {term:"inherent right", definition:"固有权利"},
  {term:"inheritance", definition:"继承；遗产"},
  {term:"injunction", definition:"禁令；强制令"},
  {term:"injustice", definition:"不公正；不法"},
  {term:"inmate", definition:"囚犯；在押人员"},
  {term:"insanity", definition:"精神失常；精神病"},
  {term:"instigate", definition:"煽动；怂恿"},
  {term:"interference with public servant", definition:"妨碍公务"},
  {term:"INTERPOL", definition:"国际刑警组织"},
  {term:"interpleader", definition:"互争权利诉讼"},
  {term:"interrogatory", definition:"书面质询"},
  {term:"interstate", definition:"州际的"},
  {term:"intimidation", definition:"恐吓；威胁"},
  {term:"intoxication", definition:"醉酒"},
  {term:"intoxilizer", definition:"酒精测试仪；酒醉测试器"},
  {term:"intestacy", definition:"无遗嘱死亡"},
  {term:"intestate", definition:"无遗嘱"},
  {term:"issue", definition:"子女；后嗣"},
  {term:"itemize", definition:"列举；详细列明J"},
  {term:"jailbreak", definition:"越狱"},
  {term:"jay-walk", definition:"违章横穿马路"},
  {term:"John/Jane Doe", definition:"无名氏；某某人"},
  {term:"joy riding", definition:"偷车兜风；无照驾驶兜风"},
  {term:"Judge Advocate General", definition:"军法局长；军法处长"},
  {term:"judicial notice", definition:"司法认知"},
  {term:"judiciary", definition:"司法系统；司法部门"},
  {term:"jurisprudence", definition:"法学；法理学"},
  {term:"jurist", definition:"法学家"},
  {term:"juror", definition:"陪审员"},
  {term:"juror, alternative", definition:"候补陪审员"},
  {term:"juror, prospective", definition:"候选陪审员"},
  {term:"juror, sworn", definition:"正式陪审员"},
  {term:"jury box", definition:"陪审团席"},
  {term:"jury instructions", definition:"法官对陪审团的指示"},
  {term:"jury tampering", definition:"干扰陪审团；贿赂陪审员"},
  {term:"jury trial", definition:"陪审团审判"},
  {term:"juvenile court", definition:"少年法庭"},
  {term:"juvenile delinquent", definition:"少年犯；未成年人罪犯"},
  {term:"joinder", definition:"合并诉讼"},
  {term:"joint tenancy", definition:"联合租赁"},
  {term:"jump bail", definition:"弃保潜逃"},
  {term:"junk dealer", definition:"旧物商贩"},
  {term:"kiting", definition:"开空头支票；票据诈骗"},
  {term:"kleptomania", definition:"盗窃狂；偷窃癖"},
  {term:"knowingly", definition:"知情地；故意地"},
  {term:"labor law", definition:"劳工法；劳动法"},
  {term:"laches", definition:"懈怠"},
  {term:"landmark decision", definition:"里程碑式判决"},
  {term:"larceny", definition:"盗窃罪"},
  {term:"laser-sight weapon", definition:"激光瞄准武器"},
  {term:"law enforcement agency", definition:"执法机构"},
  {term:"leasehold", definition:"租赁权；租赁地产"},
  {term:"legal aid", definition:"法律援助"},
  {term:"legal aide", definition:"法律助理"},
  {term:"legal tender", definition:"法定货币"},
  {term:"legalese", definition:"法律术语；法律行话"},
  {term:"legality", definition:"合法性"},
  {term:"legislation", definition:"立法"},
  {term:"legislature", definition:"立法机关"},
  {term:"leniency", definition:"宽恕；宽大处理"},
  {term:"lethal injection", definition:"注射死刑"},
  {term:"lethal weapon", definition:"致命武器"},
  {term:"letter bomb", definition:"信件炸弹"},
  {term:"lewd conduct", definition:"猥亵行为；淫秽行为"},
  {term:"liability insurance", definition:"责任保险"},
  {term:"libel", definition:"书面诽谤；诽谤罪"},
  {term:"lie detector", definition:"测谎仪"},
  {term:"lie in wait", definition:"埋伏；伏击"},
  {term:"lien", definition:"留置权；扣押权；优先权"},
  {term:"life sentence", definition:"无期徒刑；终身监禁"},
  {term:"lineup", definition:"列队辨认嫌疑犯"},
  {term:"liquidated damages", definition:"约定违约金"},
  {term:"liquidation", definition:"清算"},
  {term:"litigant", definition:"诉讼当事人"},
  {term:"living will", definition:"生前遗嘱"},
  {term:"lobbying", definition:"游说"},
  {term:"loaded weapon", definition:"上膛武器；装有弹药的武器"},
  {term:"loan shark", definition:"高利贷者"},
  {term:"lodge a complaint", definition:"投诉；报案"},
  {term:"loitering", definition:"游荡；闲荡"},
  {term:"loophole", definition:"漏洞；空子"},
  {term:"looting", definition:"洗劫；抢掠"},
  {term:"lapse", definition:"失效；届满"},
  {term:"LSD", definition:"迷幻药；麦角酸二乙酰胺"},
  {term:"lynching", definition:"私刑；私刑处死"},
  {term:"Mafia", definition:"黑手党；黑帮"},
  {term:"magistrate", definition:"治安法官；裁判官"},
  {term:"maintenance", definition:"扶养；维持"},
  {term:"mail bomb", definition:"邮件炸弹"},
  {term:"mail fraud", definition:"邮件欺诈"},
  {term:"mail theft", definition:"邮件盗窃"},
  {term:"maiming", definition:"残害；重伤"},
  {term:"making arrest", definition:"拘捕；逮捕"},
  {term:"malfeasance", definition:"不法行为；渎职"},
  {term:"malice", definition:"恶意；蓄意"},
  {term:"malicious mischief", definition:"恶意破坏财物"},
  {term:"malicious prosecution", definition:"恶意控告；恶意起诉"},
  {term:"malign", definition:"诽谤；诋毁"},
  {term:"malpractice", definition:"渎职；专业过失；失职"},
  {term:"mandamus", definition:"履行令"},
  {term:"mandate", definition:"授权；执行令"},
  {term:"mandatory", definition:"强制性的；义务的"},
  {term:"mandatory sentence", definition:"法定刑期；强制刑期"},
  {term:"manhunt", definition:"搜捕；追捕逃犯"},
  {term:"manslaughter", definition:"过失杀人；误杀"},
  {term:"marital", definition:"婚姻的"},
  {term:"marshal", definition:"执法官；法警；警长"},
  {term:"mass hysteria", definition:"集体歇斯底里"},
  {term:"material facts", definition:"重要事实；关键事实"},
  {term:"material statement", definition:"重要陈述"},
  {term:"material witness", definition:"关键证人；重要证人"},
  {term:"matter of record", definition:"有案可查的事项"},
  {term:"maxim", definition:"法律格言；准则"},
  {term:"mayhem", definition:"重伤罪；残害身体"},
  {term:"mediation", definition:"调解；调停"},
  {term:"minimum standard", definition:"最低标准"},
  {term:"minor", definition:"未成年人"},
  {term:"Miranda Rights", definition:"米兰达权利 羁押讯问（Custodial Interrogation）"},
  {term:"mischief", definition:"恶作剧；恶意损害"},
  {term:"misconduct", definition:"不法行为；不端行为"},
  {term:"misdemeanor", definition:"轻罪"},
  {term:"misleading question", definition:"误导性问题"},
  {term:"misnomer", definition:"误称；错名"},
  {term:"misquote", definition:"错误引用"},
  {term:"misrepresentation", definition:"虚假陈述"},
  {term:"mistrial", definition:"无效审判"},
  {term:"mitigating circumstances", definition:"减轻情节"},
  {term:"mitigating factors", definition:"减轻因素"},
  {term:"modus operandi", definition:"作案手法"},
  {term:"moot", definition:"假设的；非实际的"},
  {term:"moral certainty", definition:"内心确信"},
  {term:"moral turpitude", definition:"道德败坏"},
  {term:"motion denied", definition:"动议被驳回"},
  {term:"motion granted", definition:"动议被批准"},
  {term:"motive", definition:"动机"},
  {term:"mug shot", definition:"入案照片；嫌犯照"},
  {term:"municipal", definition:"市政的"},
  {term:"mutiny", definition:"兵变；叛乱"},
  {term:"moiety", definition:"一半"},
  {term:"merchant", definition:"商人"},
  {term:"mirror wills", definition:"镜像遗嘱"},
  {term:"misfeasance", definition:"不当履行"},
  {term:"narcotics", definition:"麻醉品；毒品"},
  {term:"native-born citizen", definition:"本土公民"},
  {term:"naturalization", definition:"归化；入籍"},
  {term:"negligent homicide", definition:"过失杀人"},
  {term:"negotiable", definition:"可流通的"},
  {term:"negotiable instrument", definition:"流通票据"},
  {term:"nepotism", definition:"裙带关系；任人唯亲"},
  {term:"neutrality law", definition:"中立法"},
  {term:"next of kin", definition:"近亲属"},
  {term:"night court", definition:"夜间法庭"},
  {term:"no contest", definition:"不抗辩；无争议"},
  {term:"non compos mentis", definition:"精神失常"},
  {term:"nonfeasance", definition:"不履行义务"},
  {term:"novation", definition:"债务更新"},
  {term:"nuisance", definition:"侵扰；妨害行为；扰民"},
  {term:"nullity", definition:"无效"},
  {term:"null and void", definition:"无效"},
  {term:"oath", definition:"宣誓；誓言"},
  {term:"obscene phone call", definition:"猥亵电话"},
  {term:"obscenity", definition:"淫秽；猥亵"},
  {term:"obstructing justice", definition:"妨害司法"},
  {term:"official misconduct", definition:"官员渎职"},
  {term:"on the record", definition:"记录在案"},
  {term:"open court", definition:"公开法庭"},
  {term:"opening statement", definition:"开庭陈述"},
  {term:"ordinance", definition:"法令；条例"},
  {term:"ostracism", definition:"排斥；排挤"},
  {term:"outlaw", definition:"歹徒；不法之徒"},
  {term:"outstanding warrant", definition:"未执行逮捕令"},
  {term:"overrule", definition:"驳回；推翻"},
  {term:"overt act", definition:"公开行为；明显行为P"},
  {term:"panel", definition:"陪审团名单；陪审团小组；专题小组"},
  {term:"pandering procuring", definition:"拉皮条；引诱卖淫"},
  {term:"parade permit", definition:"游行许可"},
  {term:"paradox", definition:"自相矛盾"},
  {term:"paramedic", definition:"急救人员"},
  {term:"paranoia", definition:"偏执狂"},
  {term:"pardon", definition:"赦免"},
  {term:"parole", definition:"假释"},
  {term:"partition", definition:"分割"},
  {term:"pass sentence", definition:"宣判"},
  {term:"paternity", definition:"父子关系"},
  {term:"paternity suit", definition:"生父确认诉讼"},
  {term:"peremptory", definition:"强制的；绝对的"},
  {term:"peremptory challenge", definition:"强制陪审员退席"},
  {term:"perjury", definition:"伪证"},
  {term:"per se", definition:"本身；自身"},
  {term:"personal property", definition:"动产"},
  {term:"petitioner", definition:"申请人"},
  {term:"petition the court", definition:"向法庭请愿"},
  {term:"petty theft", definition:"轻微盗窃"},
  {term:"piracy", definition:"盗版；海盗行为"},
  {term:"picket line", definition:"纠察线"},
  {term:"pistol", definition:"手枪"},
  {term:"plaintiff", definition:"原告"},
  {term:"plea", definition:"答辩；认罪"},
  {term:"plea bargain", definition:"认罪协商；辩诉交易"},
  {term:"plead not guilty", definition:"不认罪"},
  {term:"pleading", definition:"诉状"},
  {term:"plunder", definition:"抢劫；掠夺"},
  {term:"police dispatcher", definition:"警员调度员"},
  {term:"police record", definition:"警方记录"},
  {term:"precedence", definition:"优先权"},
  {term:"precedent", definition:"判例；先例"},
  {term:"prejudice", definition:"偏见；损害"},
  {term:"preliminary", definition:"初步的"},
  {term:"preliminary hearing", definition:"预审"},
  {term:"preliminary injunction", definition:"临时禁令"},
  {term:"premeditate", definition:"预谋"},
  {term:"premises", definition:"房屋；土地"},
  {term:"preponderance of the evidence", definition:"优势证据"},
  {term:"prerequisite", definition:"先决条件"},
  {term:"prescription", definition:"时效；处方"},
  {term:"prescription drugs", definition:"处方药"},
  {term:"presumption of innocence", definition:"无罪推定"},
  {term:"pre-sentence investigation", definition:"判前调查"},
  {term:"pre-sentence report", definition:"判前报告"},
  {term:"press charges", definition:"正式控告"},
  {term:"pretrial conference", definition:"庭前会议"},
  {term:"pretrial motions", definition:"庭前动议"},
  {term:"prima facie", definition:"表面证据"},
  {term:"prima facie evidence", definition:"初步证据；表面证据"},
  {term:"principal", definition:"本人；本金；主要的"},
  {term:"prior convictions", definition:"前科"},
  {term:"privity", definition:"合同关系"},
  {term:"probate", definition:"遗嘱认证"},
  {term:"probation", definition:"缓刑"},
  {term:"probation officer", definition:"缓刑官"},
  {term:"prohibition", definition:"禁令"},
  {term:"prosecution", definition:"起诉；控方"},
  {term:"prosecutor", definition:"检察官"},
  {term:"protective custody", definition:"保护性拘留"},
  {term:"protective order", definition:"保护令"},
  {term:"protest", definition:"拒付证书"},
  {term:"proviso", definition:"但书；附加条款"},
  {term:"public defender", definition:"公设辩护人"},
  {term:"public domain", definition:"公有领域"},
  {term:"public monies", definition:"公款"},
  {term:"punitive damages", definition:"惩罚性赔偿"},
  {term:"purge", definition:"销案；消除记录"},
  {term:"pursuit", definition:"追捕"},
  {term:"pathologist", definition:"病理学家"},
  {term:"patronizing a prostitute", definition:"嫖娼"},
  {term:"PCP", definition:"天使粉；苯环己哌啶"},
  {term:"pedestrian", definition:"行人"},
  {term:"per diem", definition:"每日津贴；按日计算"},
  {term:"perpetrator", definition:"作案人；肇事者"},
  {term:"port-of-entry", definition:"入境口岸"},
  {term:"possession of narcotics", definition:"持有毒品"},
  {term:"post bail", definition:"缴纳保释金"},
  {term:"pound", definition:"动物收容栏"},
  {term:"prank", definition:"恶作剧"},
  {term:"price fixing", definition:"价格垄断"},
  {term:"prison guard", definition:"狱警"},
  {term:"prison term", definition:"刑期"},
  {term:"privileged information", definition:"保密信息"},
  {term:"pro se", definition:"自辩；自行代理"},
  {term:"probable cause", definition:"合理依据；可能原因"},
  {term:"quack", definition:"庸医；冒牌医生"},
  {term:"quarantine", definition:"检疫隔离"},
  {term:"quash", definition:"撤销；废止"},
  {term:"quitclaim", definition:"免责转让契据"},
  {term:"quasi", definition:"准；类似"},
  {term:"quibble", definition:"狡辩"},
  {term:"quid pro quo", definition:"交换条件"},
  {term:"quorum", definition:"法定人数"},
  {term:"quota system", definition:"配额制"},
  {term:"race", definition:"种族"},
  {term:"racial discrimination", definition:"种族歧视"},
  {term:"racial segregation", definition:"种族隔离"},
  {term:"racism", definition:"种族主义"},
  {term:"racketeering", definition:"敲诈勒索；有组织犯罪"},
  {term:"radar detector", definition:"雷达探测器"},
  {term:"radar speed gun", definition:"测速雷达"},
  {term:"radical", definition:"激进的"},
  {term:"railroad crossing", definition:"铁路道口"},
  {term:"ransack", definition:"洗劫；搜查"},
  {term:"ransom", definition:"赎金"},
  {term:"rap sheet", definition:"犯罪记录"},
  {term:"ratify", definition:"批准；认可"},
  {term:"reasonable doubt", definition:"合理怀疑"},
  {term:"rebuttal", definition:"反驳；辩驳"},
  {term:"recall a witness", definition:"传唤证人"},
  {term:"receiving stolen property", definition:"窝赃"},
  {term:"reckless burning", definition:"鲁莽纵火"},
  {term:"reckless driving", definition:"鲁莽驾驶"},
  {term:"recognizance", definition:"具结保证"},
  {term:"reconciliation", definition:"和解；调解"},
  {term:"recess", definition:"休庭；休息"},
  {term:"recidivist", definition:"累犯；惯犯"},
  {term:"recross", definition:"再次盘问"},
  {term:"redirect", definition:"再次询问"},
  {term:"reinstate", definition:"恢复；复职"},
  {term:"release pending trial", definition:"保释待审"},
  {term:"remand", definition:"还押；押回再审"},
  {term:"remission", definition:"减免"},
  {term:"reparations", definition:"赔偿；补偿"},
  {term:"repatriation", definition:"遣返"},
  {term:"repeat offender", definition:"累犯"},
  {term:"restitution", definition:"返还；赔偿"},
  {term:"restraining order", definition:"限制令；保护令"},
  {term:"restraint", definition:"限制"},
  {term:"resting", definition:"静止"},
  {term:"retaliation", definition:"报复"},
  {term:"reverse", definition:"撤销；推翻"},
  {term:"reversion", definition:"复归权"},
  {term:"revocation", definition:"撤销；废除"},
  {term:"riparian rights", definition:"河岸权"},
  {term:"riot", definition:"暴乱；骚乱"},
  {term:"ruling", definition:"裁定；判决"},
  {term:"rebuttal", definition:"反驳"},
  {term:"recusal", definition:"回避"},
  {term:"redemption", definition:"赎回"},
  {term:"reimbursement", definition:"偿还"},
  {term:"replevin", definition:"追回动产之诉"},
  {term:"rescission", definition:"撤销"},
  {term:"residue", definition:"剩余遗产"},
  {term:"res judicata", definition:"既判力"},
  {term:"restrictive covenant", definition:"限制性契约"},
  {term:"retainer", definition:"律师费；聘用"},
  {term:"retention", definition:"保留"},
  {term:"satisfaction", definition:"清偿"},
  {term:"scienter", definition:"明知"},
  {term:"search warrant", definition:"搜查令"},
  {term:"secretary of state", definition:"州务卿；国务卿"},
  {term:"sentencing", definition:"宣判；量刑"},
  {term:"separate property", definition:"个人财产"},
  {term:"sexual assault", definition:"性侵犯"},
  {term:"sexual harassment", definition:"性骚扰"},
  {term:"shield law", definition:"新闻保护法"},
  {term:"shoplifting", definition:"入店行窃"},
  {term:"sickness benefit", definition:"疾病补助"},
  {term:"slander", definition:"口头诽谤"},
  {term:"solicit", definition:"教唆；引诱"},
  {term:"speedy trial", definition:"快速审判"},
  {term:"statute", definition:"成文法；法规"},
  {term:"statute of limitations", definition:"诉讼时效；时效法"},
  {term:"statutory", definition:"法定的"},
  {term:"stolen property", definition:"赃物"},
  {term:"stop and frisk", definition:"拦截拍身搜查"},
  {term:"subpoena", definition:"传票"},
  {term:"subpoena duces tecum", definition:"证据传票"},
  {term:"subrogation", definition:"代位权"},
  {term:"summons", definition:"传唤；传票"},
  {term:"suppress", definition:"压制；排除（证据）"},
  {term:"supremacy", definition:"至高无上；主权"},
  {term:"surveillance", definition:"监视；监控"},
  {term:"suspension", definition:"暂停；中止"},
  {term:"sworn", definition:"宣誓的；起誓的"},
  {term:"servient estate", definition:"供役地"},
  {term:"sheriff", definition:"警长"},
  {term:"solemn", definition:"庄严的"},
  {term:"specific performance", definition:"强制履行"},
  {term:"sunset", definition:"日落条款"},
  {term:"surety", definition:"保证人"},
  {term:"survivorship", definition:"生存者取得权"},
  {term:"testament", definition:"遗嘱"},
  {term:"testator", definition:"立遗嘱人"},
  {term:"testimony", definition:"证言；证词"},
  {term:"tort", definition:"侵权行为"},
  {term:"tortfeasor", definition:"侵权人"},
  {term:"traffic court", definition:"交通法庭"},
  {term:"traffic violation", definition:"交通违章"},
  {term:"treason felony", definition:"叛国重罪"},
  {term:"treble damages", definition:"三倍赔偿"},
  {term:"trespass", definition:"非法侵入；侵权"},
  {term:"trial by jury", definition:"陪审团审判"},
  {term:"trial court", definition:"初审法院；审判法庭"},
  {term:"tribunal", definition:"裁判庭；特别法庭"},
  {term:"try", definition:"审理；审判"},
  {term:"tenancy", definition:"租赁"},
  {term:"tenant", definition:"承租人"},
  {term:"tender", definition:"要约；支付"},
  {term:"tenement", definition:"不动产"},
  {term:"undue influence", definition:"不当影响"},
  {term:"unicameral", definition:"一院制"},
  {term:"uniform", definition:"统一的"},
  {term:"unilateral", definition:"单方的"},
  {term:"uphold", definition:"维持；确认（原判）"},
  {term:"usufruct", definition:"用益权"},
  {term:"usury", definition:"高利贷"},
  {term:"utensil", definition:"器具；用具"},
  {term:"vacate", definition:"撤销；使无效"},
  {term:"variance", definition:"变更；差异"},
  {term:"vendee", definition:"买受人"},
  {term:"vendor", definition:"出卖人"},
  {term:"venue", definition:"审判地；管辖地"},
  {term:"verdict", definition:"裁决；判决"},
  {term:"versus", definition:"对；诉"},
  {term:"veto", definition:"否决"},
  {term:"vicarious liability", definition:"替代责任"},
  {term:"voir dire", definition:"陪审员遴选"},
  {term:"voucher", definition:"凭证；单据"},
  {term:"warrant", definition:"令状；搜查令；逮捕令；担保"},
  {term:"warranty", definition:"担保；保证"},
  {term:"waste", definition:"毁损"},
  {term:"witness stand", definition:"证人席"},
  {term:"writ", definition:"令状；书面命令"},
  {term:"wrongful death", definition:"非法致死；非正常死亡"},
  {term:"young offender", definition:"青少年罪犯"},
  {term:"zero tolerance", definition:"零容忍"},
  {term:"ab initio", definition:"自始；从一开始（from the beginning）"},
  {term:"a fortiori", definition:"更有理由；何况（with stronger reason）"},
  {term:"bona fide", definition:"善意；真诚（in good faith）"},
  {term:"mala fide", definition:"恶意（in bad faith）"},
  {term:"de facto", definition:"事实上；实际（in fact）"},
  {term:"de jure", definition:"法律上；法定（by law）"},
  {term:"ex officio", definition:"依职权（by virtue of office）"},
  {term:"ex post facto", definition:"事后；溯及既往（after the fact）"},
  {term:"inter alia", definition:"除其他外；尤其（among other things）"},
  {term:"mutatis mutandis", definition:"作必要修改后（with necessary changes）"},
  {term:"per se", definition:"本身；本质上（by itself）"},
  {term:"pro bono", definition:"公益性；无偿法律服务（for the public good）"},
  {term:"ubi jus ibi remedium", definition:"有权利必有救济（where there is a right, there is a"},
  {term:"remedy）lex non cogit ad impossibilia", definition:"法律不强人所难（the law does not"},
  {term:"nemo iudex in causa sua", definition:"任何人不得为自己案件的法官（no one is judge in"},
  {term:"ad litem", definition:"专为诉讼指定的（for the suit）"},
  {term:"amicus curiae", definition:"法庭之友（friend of the court）"},
  {term:"corpus delicti", definition:"犯罪事实；罪体（body of the crime）"},
  {term:"de novo", definition:"重新审理（anew; from the beginning）"},
  {term:"ejusdem generis", definition:"同类规则（of the same kind）"},
  {term:"ex parte", definition:"单方面的；片面的（one party only）"},
  {term:"forum non conveniens", definition:"不方便法院原则（inconvenient forum）"},
  {term:"habeas corpus", definition:"人身保护令（you have the body）"},
  {term:"in camera", definition:"不公开审理；秘密审讯（in private）"},
  {term:"in personam", definition:"对人（诉讼/权利）（against the person）"},
  {term:"in rem", definition:"对物（诉讼/权利）（against the thing）"},
  {term:"lis pendens", definition:"未决诉讼（pending lawsuit）"},
  {term:"locus standi", definition:"诉讼资格；出庭资格（standing to sue）"},
  {term:"mandamus", definition:"履行令；强制令（we command）"},
  {term:"noscitur a sociis", definition:"文理解释；由上下文知其意（known by its associates）"},
  {term:"res judicata", definition:"既判力；一事不再理（a matter judged）"},
  {term:"stare decisis", definition:"遵循先例（stand by decided matters）"},
  {term:"sub judice", definition:"正在审理中（under judgment）"},
  {term:"subpoena", definition:"传票（under penalty）"},
  {term:"a mensa et thoro", definition:"法定分居（from bed and board）"},
  {term:"flagrante delicto", definition:"现行犯；当场（in the very act of committing a crime）"},
  {term:"prima facie", definition:"初步证据；表面确凿（at first sight）"},
  {term:"res gestae", definition:"事实行为；事件陈述（things done）"},
  {term:"res ipsa loquitur", definition:"事实自证（the thing speaks for itself）"},
  {term:"expressio unius est exclusio alterius", definition:"明示其一即排除其他（expression of"},
  {term:"volenti non fit injuria", definition:"自愿承担风险（to a willing person, no injury is"},
  {term:"caveat emptor", definition:"买者自负（buyer beware）"},
  {term:"consensus ad idem", definition:"合意；意思一致（meeting of the minds）"},
  {term:"quantum meruit", definition:"按合理价值给付；不当得利返还（as much as he deserves）"},
  {term:"quid pro quo", definition:"等价交换；对价（something for something）"},
  {term:"damnum absque injuria", definition:"有损害无侵权（harm without legal wrong）"},
  {term:"generalia specialibus non derogant", definition:"特别法优于一般法（general things do"},
  {term:"pari passu", definition:"同等地位；按比例（equally; without preference）"},
  {term:"solutio sine causa", definition:"无因给付（payment without cause）"},
  {term:"bona vacantia", definition:"无主财产（ownerless property）"},
  {term:"cy pres", definition:"近似原则（as near as possible）"},
  {term:"nemo dat quod non habet", definition:"不得出让不属于自己的权利（no one gives what they"},
  {term:"per capita", definition:"按人头（继承）（by head）"},
  {term:"per stirpes", definition:"按支系（继承）（by branch）"},
  {term:"per autre vie", definition:"为他人终身（for another\\'s life）"},
  {term:"terra nullius", definition:"无主地（nobody's land）"},
  {term:"ultra vires", definition:"越权（beyond power）"},
  {term:"ubi panis ibi rex", definition:"有财产即有主权（where there is property, there is"},
  {term:"actus reus", definition:"犯罪行为（客观要件）（guilty act）"},
  {term:"mens rea", definition:"犯罪意图（主观要件）（guilty mind）"},
  {term:"capax doli", definition:"犯罪能力（capacity for crime）"},
  {term:"in loco parentis", definition:"代行父母职责（in place of a parent）"},
  {term:"non compos mentis", definition:"精神失常；无行为能力（not of sound mind）"},
  {term:"non sequitur", definition:"不合逻辑的推论（it does not follow）"},
  {term:"obiter dictum", definition:"附带意见（by the way）"},
  {term:"ratio decidendi", definition:"判决理由（reason for deciding）"},
  {term:"ex abundanti cautela", definition:"格外谨慎；以防万一（out of abundant caution）"},
  {term:"ex facie", definition:"从表面上看（on the face of it）"},
  {term:"ex gratia", definition:"特惠；无偿（as a favor）"},
  {term:"in pari materia", definition:"同类事项；相关法律（on the same subject matter）"},
  {term:"et alii (et al.)", definition:"以及其他人（and others）"},
  {term:"ipso facto", definition:"依据事实本身（by the fact itself）"},
  {term:"nunc pro tunc", definition:"追溯生效（now for then）"},
  {term:"proviso", definition:"但书；附加条款（provided that）"},
  {term:"quorum", definition:"法定人数（sufficient number）"},
  {term:"sub rosa", definition:"秘密地；私下（under the rose）"},
  {term:"vice versa", definition:"反之亦然（the other way around）"},
  {term:"videlicet (viz.)", definition:"即；就是（namely）"},
];